### ISSUE TITLE
Too long string 

### ISSUE THREAD

**Issue by itmayi** [komiya-atsushi/xgboost-predictor-java#40]
when i use XGBoostPredictor load one model to do a test, one exception happenned. How can i sovle it? 
```
Predictor predictor = new Predictor(
                new `java.io.FileInputStream("./model/ransom.pickle"));
```

Exception in thread "main" java.io.IOException: Too long string: 7887331693998180980
	at biz.k11i.xgboost.util.ModelReader.readString(ModelReader.java:185)
	at biz.k11i.xgboost.Predictor.readParam(Predictor.java:108)
	at biz.k11i.xgboost.Predictor.<init>(Predictor.java:43)
	at biz.k11i.xgboost.Predictor.<init>(Predictor.java:26)
	at HowToUseXgboostPredictor.main(HowToUseXgboostPredictor.java:16)

**Comment by ajolivard** [comment]
Hi, I have the same issue. Did you find out what the problem was ?

**Comment by popfido** [comment]
I guess u guys save the model in a wrong format.

Predictor seems only accept models saved by booster

if you use sklearn.joblib or directly pickle it down, it may cannot be loaded

**Comment by matrixnl** [comment]
@itmayi Hi, Did you find a workaround?
